### ISSUE TITLE
Alejandro: encapsulation, Week 1

### ISSUE THREAD

**Issue by AlejoVE** [HackYourFutureBelgium/class-8#257]
### Prep Work

- [x] Object Methods: this
- [x] What is Object Oriented Programming? (1)
- [x] What is Object Oriented Programming? (2)
- [x] javascript.info

## Project: practical-javascript 
---
- [repository](https://github.com/AlejoVE/practical-javascript)
- [live demo](https://alejove.github.io/practical-javascript/)

### Branches

- [html](https://github.com/AlejoVE/practical-javascript/tree/html)
- [data](https://github.com/AlejoVE/practical-javascript/tree/data)
- [handlers](https://github.com/AlejoVE/practical-javascript/tree/handlers)
- [onclick events](https://github.com/AlejoVE/practical-javascript/tree/onclick-events)
- [view](https://github.com/AlejoVE/practical-javascript/tree/view)
- [css](https://github.com/AlejoVE/practical-javascript/tree/css)

#### Isolating JavaScript
 - [x]  Fork [functions-to-methods](https://github.com/AlejoVE/functions-to-methods)
       -[ ] solve each one on a separate branch and merge to master when they are complete
 - [x] Fork [numbery-organizer](https://github.com/AlejoVE/numbery-organizer)
       - [ ] solve each one on a separate branch and merge to master when they are complete
- [x] Fork [getters-and-setters](https://github.com/AlejoVE/getters-and-setters)
      - [ ] solve each one on a separate branch and merge to master when they are complete

**Comment by Toinne** [comment]
👍 Nicezzz

- Don't forget to format your css a bit.
Make it easier to read for future you and other developers.
https://github.com/AlejoVE/practical-javascript/blob/css/style.css

- You can align stuff to the center much easier. Remember `Flexbox` ?
```css
body {
    height: 100vh; /* makes sure the body takes up the entire height of the viewport */
    justify-content: center; /* center the children horizontally */
    align-items: center; /* center the children vertically */
}

.centered {
    padding-top: 25px;
    width: 60%;
    background-color: #e1e1ea;
    text-align: center;
}
```
Cool right much shorter and way easier to understand.


Not seeing any completed exercise. Did you forget to push ? 

https://github.com/AlejoVE/numbery-organizer/blob/master/object.js
https://github.com/AlejoVE/getters-and-setters/blob/master/getters/refactor-1.js
https://github.com/AlejoVE/functions-to-methods/blob/master/challenges/refactor-1.js
